name: "Duplicate code"

on:
  pull_request:
    types: [opened, reopened]
  issue_comment:
    types: [created, edited, deleted]
permissions:
  contents: read
  pull-requests: write

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, 'run_duplicate_code_detection')
    steps:
      - name: Check for duplicate code(core)
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "core"
          ignore_directories: "core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/exceptionï¼Œ core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/constraint"
          file_extensions: "java, py"
          # Only report similarities above x%
          ignore_below: 80
          # If a file is more than x% similar to another, then the job fails
          fail_above: 90
          # If a file is more than x% similar to another, show a warning symbol in the report
          warn_above: 85
          one_comment: true
          header_message_start: "## ðŸ“Œ Duplicate code detection tool report (core)"

      - name: Check for duplicate code(datasource)
        if: always()
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "dataSources"
          file_extensions: "java, py"
          ignore_below: 80
          fail_above: 90
          warn_above: 85
          one_comment: true
          header_message_start: "## ðŸ“Œ Duplicate code detection tool report (datasource)"

      - name: Check for duplicate code(session, shared)
        if: always()
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "session, shared"
          file_extensions: "java, py"
          ignore_below: 70
          fail_above: 90
          warn_above: 80
          one_comment: true
          header_message_start: "## ðŸ“Œ Duplicate code detection tool report (session, shared)"
